name: methane-policy-iiasa
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - nbstripout
  - matplotlib
  - numpy
  - pandas
  - scipy
  - tqdm
# if you need to pip install anything:
  - pip
  - pip:
    - -e ../fair2.1-calibrate
