name: methane-mitigation
channels:
  - chrisroadmap
  - conda-forge
dependencies:
  - fair==2.1.3
  - jupyter
  - nbstripout
  - matplotlib
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - statsmodels
  - tqdm
