name: methane-policy-iiasa
channels:
  - conda-forge
  - defaults
dependencies:
  - h5py
  - jupyter
  - nbstripout
  - matplotlib
  - numpy
  - pandas
  - scipy
  - tqdm
# if you need to pip install anything:
  - pip
  - pip:
    - fair==2.1.0
    - aneris-iamc
